theme: jekyll-theme-dinky
title: IFTTT Chrome Buttons , How to use IFTTT maker channel
description: unofficial chrome extension which has a functionality of IFTTT do button
google_analytics: UA-67475585-2
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
