theme: jekyll-theme-cayman
title: IFTTT Chrome Buttons
description: "This extension's functionality is same as that of an IFTTT DO button but in chrome"
google_analytics: UA-67475585-2
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
